config/routes.rb
Timetracker::Application.routes.draw do
  resources :logs

  resources :employers
  resources :holidays
  resources :projects
  resources :tasks
  resources :teams
  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  root to: 'pages#home'
  match '/login',           to: 'sessions#new',          via: 'get'
  match '/logout',          to: 'sessions#destroy',      via: 'delete'
  match '/select_employer', to: 'pages#select_employer', via: ['get', 'post']
  match '/timetable',       to: 'timetables#show',       via: 'get'
  match '/timetable',       to: 'timetables#update',     via: 'post'
  match '/reports',         to: 'reports#configure',     via: 'get'
  match '/reports',         to: 'reports#generate',      via: 'post'
  match '/help',            to: 'pages#help',            via: 'get'

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to image_tag('logo.png', :title => "Timetracker"), root_path, id: "logo" %>
      <div class="nav-control">
        <% if logged_in? and multiple_employers? %>
          <div class="pull-right">
            <%= form_tag(select_employer_url, :id => 'switch_employer') do %>
                <%= button :employer %>
                <%= select_tag :selected_employer_id,
                    options_from_collection_for_select(@available_employers, :id, :name, selected_employer_id),
                    :prompt   => (is_employer_selected? ? nil : "- Select a employer -"),
                    :disabled => !multiple_employers?,
                    :onchange => ("$('#switch_employer').submit()") %>
            <% end %>
          </div>
        <% end %>
        <nav>
          <ul class="nav pull-right">
            <li><%= link_to button(:home, 'Home'), root_path %></li>
            <li><%= link_to button(:report, "Report"), reports_path %></li>
            <% if logged_in? %>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= button :account, 'Account' %> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to button(:user, "Profile"), edit_user_path(current_user) %></li>
                  <li><%= link_to button(:timetable, "Time table"), timetable_path %></li>
                  <!--<li><%= link_to "Settings", '#' %></li>-->
                  <!--<li class="divider"></li>-->
                  <!--<li><%= link_to button(:logout, "Logout"), logout_path, method: "delete" %></li>-->
                </ul>
              </li>
              <% if current_user.is_manager? or current_user.is_manager_of?(selected_employer) %>
                <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <%= button :manage, 'Manage' %> <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to button(:employer, "Employers"), employers_path if current_user.is_manager? %></li>
                    <li><%= link_to button(:edit, "Edit employer"), edit_employer_path(selected_employer) if is_employer_selected? and current_user.is_manager_of?(selected_employer) and not current_user.is_manager? %></li>
                    <li><%= link_to button(:users, "Users"), users_path if current_user.is_admin? %></li>
                    <li><%= link_to button(:team, "Teams"), teams_path if is_employer_selected? and current_user.is_manager_of?(selected_employer) %></li>
                    <li><%= link_to button(:project, "Projects"), projects_path if is_employer_selected? and current_user.is_manager_of?(selected_employer) %></li>
                    <li><%= link_to button(:task, "Tasks"), tasks_path if current_user.is_manager? %></li>
                    <li><%= link_to button(:holiday, "Holidays"), holidays_path if is_employer_selected? and current_user.is_manager_of?(selected_employer) %></li>
                  </ul>
                </li>
              <% end %>
              <!--<% if current_user.is_admin? %>-->
                <!--<li id="fat-menu" class="dropdown">-->
                  <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown">-->
                    <!--<%= button :admin, 'Admin' %> <b class="caret"></b>-->
                  <!--</a>-->
                  <!--<ul class="dropdown-menu">-->
                    <!--<li><%= link_to button(:users, "Users"), users_path %></li>-->
                  <!--</ul>-->
                <!--</li>-->
              <!--<% end %>-->
              <li><%= link_to(button(:logout, "Logout"), logout_path, method: "delete") unless @basic_auth %></li>
            <% else %>
              <li><%= link_to "Login", login_path%></li>
            <% end %>
            <!--<li><%= link_to button(:help, "Help"), help_path %></li>-->
          </ul>
        </nav>
      </div>
    </div>
  </div>
</header>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'raphael-min', 'g.raphael-min', 'g.pie-min'  %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
        <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
        <!-- %= render 'layouts/footer' %-->
        <!--<%= debug(params) if Rails.env.development? %>-->
    </div>
</body>
</html>